name: "Antora Build"
description: "Generate the a site with Antora."
branding:
  icon: book-open
  color: green
inputs:
  playbook:
    description: 'The playbook file to use.'
    required: false
    default: 'antora-playbook.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.playbook}}